# Generated by Django 3.2.13 on 2022-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='duration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='quantity',
            field=models.TextField(),
        ),
    ]
