# Generated by Django 3.2.13 on 2022-09-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftthapp', '0002_auto_20220919_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='speed',
            field=models.TextField(),
        ),
    ]
