# Generated by Django 3.2.13 on 2022-09-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftthapp', '0003_alter_pricing_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.TextField(),
        ),
    ]
